version: "3"
services:
  grafana_influx:
    container_name: "grafana-influx-nginx_grafana_influx"
    ports:
      - "8080:80"
      - "3000:3000"
    volumes:
      - ./data:/var/www/localhost
    build:
      dockerfile: Dockerfile
      context: ./