version: "3"
services:
  grafana_influx:
    # image: pilifs/grafana-influx:7
    container_name: "grafana_influx"
    ports:
      - "8080:80"
      - "3001:3000"
    build:
      dockerfile: Dockerfile
      context: ./